### PR TITLE
Map initialisms in a nice way

### PR DESCRIPTION
**Pull request by phsmit**
Implementation of this: https://github.com/go-xorm/xorm/issues/197

### CODE REVIEW

**Comment by lunny** [comment]
I think this is more gonic. But for compatible, I think we cannot change the default mapper. So I think this could be a new optional mapper but a default mapper. Could you please change it as a new mapper and pull request again?

**Comment by phsmit** [comment]
Sure. Do you have a suggestion for the name of this mapper?

**Comment by lunny** [comment]
```GoMapper``` or  ```GonicMapper``` ?

**Comment by phsmit** [comment]
I have implemented it now as GonicMapper, but I'm not so sure "Gonic" is used very often...

**Comment by lunny** [comment]
I think maybe we need an especial method for user to custom his Initialisms which is not in commonInitialisms. So we could define GonicMapper below:
```Go
type GonicMapper map[string]bool
// or
type GonicMapper struct {
     Initialisms map[string]bool
}
```

**Comment by phsmit** [comment]
Ok, I made it a map and created a LintGonicMapper as an initialized version

**Comment by lunny** [comment]
Thanks.

**Pull request merged**
