### PR TITLE
Add UniqueIdentifier type for supporting mssql

### PR DESCRIPTION
**Pull request by p581581**
Add UniqueIdentifier type and recognize it as byte array.

### CODE REVIEW

**Comment by lunny** [comment]
Is `UniqueIdentifier` similar with `UUID` type? Maybe we should return `string` but not `[]byte`?

**Comment by p581581** [comment]
Yeah, it is `UUID` type. But, for now, it parses incorrectly, if we recognize it as `string`. Also, `UUID` is a 128-bit number which would be faster than `Varchar(36)`.

**Comment by lunny** [comment]
@p581581 I cannot confirm that. Have you run this patch successfully?

**Comment by p581581** [comment]
Yeah, it works fine, but still need to parse it to string when passing parameter.

**Comment by lunny** [comment]
@p581581 Thanks!

**Pull request merged**
