### PR TITLE
Add interface for Engine & Session

### PR DESCRIPTION
**Pull request by tamalsaha**
We would like to mock Engine and Session structs in our code using https://github.com/golang/mock . To do that we need `interface` for Engine and Session. Changes required are:
- Add the new interfaces to core package.
- Update xorm pkg's implementation to match these new interfaces. The main change required is to use use the Session interface in xorm.Engine struct. It be something like: https://github.com/go-xorm/xorm/compare/master...appscode:mock?expand=1

@lunny, does this sound acceptable?

### CODE REVIEW

**Comment by lunny** [comment]
this is also fix #1501

**Comment by lunny** [comment]
Looks great but I don't know how to use mock to do tests.

**Comment by TamalSaha** [comment]
@lunny , basically you can generate a mock implementation based on the interface (or use a reflection based mock). The mock records calls and args. Unit tests can check for those. See docs here: https://godoc.org/github.com/golang/mock/gomock

One more thing that needs to be added to Session is `AutoClose()`.

**Comment by lunny** [comment]
@tamalsaha see https://github.com/go-xorm/xorm/blob/master/interface.go

**Pull request closed without merging**
